services: 
  
  redis:
    image: redis
    volumes: 
      - redisStorage:/data    
  counter: 
    build: ./Counter
    volumes:
      - ./Counter/src://var/www/src
    ports: 
      - 5000:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis
    links: 
      - redis

  bookshop: 
    build: ./BookShop
    volumes:
      - ./BookShop/src://var/www/src
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_HOST=counter
      - COUNTER_PORT=3002            
      - DB_NAME=${DB_NAME:-books_database}  
    env_file:
      - ./BookShop/.atlas.env    
    links:
      - counter
    
volumes:
  redisStorage: